# 服务端口


#数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: 123456
    druid:
      #初始化连接大小
      initial-size: 8
      #最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 10
      #查询超时时间
      query-timeout: 6000
      #事务查询超时时间
      transaction-query-timeout: 6000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800
      filters: stat,config

mybatis-plus:
  # 指定sql映射文件位置
  mapper-locations:
    - classpath:/mapper/*Mapper.xml
    - mapper*/DynamicSqlMapper.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0